openapi: "3.0.3"
info:
  title: "DisGloss API Spec"
  description: "The APIs used by the DisGloss discord bot"
  version: "0.0.1"
  contact:
    name: "Ben Lewis"
    url: "https://github.com/benji-lewis"
    email: "oss@benjilewis.dev"
servers:
  - url: "https://gloss-worker.xfour.workers.dev"
    description: "The standard API endpoint for DisGloss interactions"
paths:
  /config/{guildId}/{channelId}:
    head:
      operationId: "getChannelConfig"
      tags:
        - "Config"
      summary: "Check whether a channel should be cached"
      description: "This endpoint will return either 200 or 404 dependent on whether the channel has been enabled as a glossary channel."
      parameters:
        - in: "path"
          name: "guildId"
          schema:
            type: "string"
          required: true
          allowEmptyValue: false
        - in: "path"
          name: "channelId"
          schema:
            type: "string"
          required: true
          allowEmptyValue: false
      responses:
        200:
          description: "Indicates that the channel should be cached"
        404:
          description: "Indicates the channel should not be cached"
        default: "#/components/responses/GenericError"
    post:
      operationId: "enableConfig"
      tags:
        - "Config"
      summary: "Enables glossary functionality on a channel"
      description: "When this endpoint is called, the channel is enabled for DisGloss monitoring."
      parameters:
        - in: "path"
          name: "guildId"
          schema:
            type: "string"
          required: true
          allowEmptyValue: false
        - in: "path"
          name: "channelId"
          schema:
            type: "string"
          required: true
          allowEmptyValue: false
      responses:
        202:
          description: "Caching has been enabled on the channel"
        default:
          description: "There has been an issue enabling caching on the channel"
    delete:
      operationId: "disableConfig"
      tags:
        - "Config"
      summary: "Disables glossary functionality on a channel"
      description: "When this endpoint is called, the channel is disabled for DisGloss monitoring."
      parameters:
        - in: "path"
          name: "guildId"
          schema:
            type: "string"
          required: true
          allowEmptyValue: false
        - in: "path"
          name: "channelId"
          schema:
            type: "string"
          required: true
          allowEmptyValue: false
      responses:
        202:
          description: "Caching has been disabled on the channel"
        default:
          description: "There has been an issue enabling caching on the channel"
  /definition:
    get:
      operationId: "getDefinition"
      description: "Fetches all instances of the term from the server glossary."
      parameters:
        - in: "query"
          name: "term"
          schema:
            type: "string"
          required: true
          allowEmptyValue: false
        - in: "query"
          name: "definition"
          schema:
            type: "string"
          required: true
          allowEmptyValue: false
      responses:
        200:
          description: "Definition(s) have been found"
  /:
    post:
      operationId: "queueMessage"
      tags:
        - "Queue"
      summary: "Adds a message to the processing queue"
      description: "Messages can be formatted here in Discord format to prepare for batch processing."
      responses:
        default:
          description: "TBC"
      servers:
        - url: "https://gloss-queue.xfour.workers.dev/"
          description: "The endpoint used for queuing messages."
components:
  responses:
    GenericError:
      description: "An unexpected error occurred"
